### ISSUE TITLE
head fragment 이슈

### ISSUE THREAD

**Issue by hahakang7** [bangbang444/MythOfNovice#22]
head fragemt 일단 forgot password, signup, login 에 적용하였습니다.
그런데 signup의 성별선택이랑 login의 사진 css적용에 문제가 있습니다.
인지하고있으니 추후 수정할것입니다

**Comment by hahakang7** [comment]
해결 하긴했는데 맘에 안들어요

**Comment by DingWoonee** [comment]
뭐가 맘에 안들죠?

**Comment by hahakang7** [comment]
원래 코드는 th:insert 를 이용해서 하는데 insert면 이전 코드에 사라지는게 아니라 추가가 되야할것같은데 적용이 완되서 그냥 th:block만들고 replace로 했어요
